name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  version:
    description: 'The version '
    required: true
    default: 'World'    
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'